### ISSUE TITLE
windows user

### ISSUE THREAD

**Issue by gim4p** [gim4p/cruise_track_tool#14]
If user only wants to download Zip-file and wants to use the "installing from Zip"-opportunity in QGis/
or might not find the plugin folder (C:\Users\gia\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins).
the right package should be additionally directly zipped for download (as option).

Could also be inserted as Zip-installation-download-link.

In November I read about ways for implementing this. Should be feaible when there is time.

**Comment by MBennGit** [comment]
duplicate of #10
